//edit by Jerry
//2008.11.17

string *room_maps=({
		"/d/jfjwm/room/room1",
		"/d/jfjwm/room/room2",
		"/d/jfjwm/room/room3",
		"/d/jfjwm/room/room4",
		"/d/jfjwm/room/room5",
		"/d/jfjwm/room/room6",
		"/d/jfjwm/room/room7",
		"/d/jfjwm/room/room8",
		"/d/jfjwm/room/room9",
		"/d/jfjwm/room/room10",
		"/d/jfjwm/room/room11",
		"/d/jfjwm/room/room12",
		"/d/jfjwm/room/room13",
		"/d/jfjwm/room/room14",
		"/d/jfjwm/room/room15",
		"/d/jfjwm/room/room16",
		"/d/jfjwm/room/room17",
		"/d/jfjwm/room/room18",
		"/d/jfjwm/room/room19",
		"/d/jfjwm/room/room20",
		"/d/jfjwm/room/room21",
		"/d/jfjwm/room/room22",
		"/d/jfjwm/room/room23",
		"/d/jfjwm/room/room24",
		"/d/jfjwm/room/room25",
		"/d/jfjwm/room/room26",
		"/d/jfjwm/room/room27",
		"/d/jfjwm/room/room28",
		"/d/jfjwm/room/room29",
		"/d/jfjwm/room/room30",
});