//防止转码错乱
mapping finish_obj = ([	
    0 : "/d/fuben_jiaofei/obj/putao",
	1 : "/d/fuben_jiaofei/obj/putao",
	2 : "/d/fuben_jiaofei/obj/putao",
	3 : "/d/fuben_jiaofei/obj/butian",
	4 : "/d/fuben_jiaofei/obj/dan_bianxing",
	5 : "/d/fuben_jiaofei/obj/jinsha",
	6 : "/d/fuben_jiaofei/obj/jinsha",
	7 : "/d/fuben_jiaofei/obj/jinsha",
	8 : "/clone/shizhe/dan_xixin",
	9 : "/d/fuben_jiaofei/obj/card_name",
	10 : "/d/fuben_jiaofei/obj/butian_suipian",
	11 : "/d/fuben_jiaofei/obj/butian_suipian",
	12 : "/d/fuben_jiaofei/obj/butian_suipian",
	13 : "/d/fuben_jiaofei/obj/putao1",
	14 : "/d/fuben_jiaofei/obj/zhuisha",
	15 : "/d/fuben_jiaofei/obj/zhuisha",
	16 : "/d/fuben_jiaofei/obj/zhuisha",
	17 : "/d/fuben_jiaofei/obj/zhuisha",
	18 : "/d/fuben_jiaofei/obj/zhuisha",
]);